<?php
$orderFilters = $orderFilters ?? ['search' => '', 'status' => '', 'product_id' => '', 'location' => '', 'sort' => 'created_desc'];
$products = $products ?? [];
$orderStats = $orderStats ?? ['total_orders' => 0, 'total_units' => 0, 'total_revenue' => 0, 'pending_orders' => 0, 'shipped_orders' => 0, 'cancelled_orders' => 0];
?>
<style>
.order-stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin:20px 0}
.order-stat-card{padding:20px;border-radius:20px;background:linear-gradient(180deg,#fff 0%,#f8fbff 100%);border:1px solid #dbe7f3;box-shadow:0 18px 40px rgba(15,23,42,.06)}
.order-stat-card strong{display:block;font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#64748b}
.order-stat-card .metric{display:block;font-size:31px;font-weight:800;color:#0f172a;margin-top:8px}
.order-stat-card .meta{display:block;font-size:13px;color:#475569;margin-top:8px;line-height:1.5}
</style>
<div id="orders-live-panel">
<div class="card">
    <div class="header-line">
        <div>
            <h1 style="margin:0"><?= htmlspecialchars($pageTitle ?? 'Orders', ENT_QUOTES, 'UTF-8') ?></h1>
            <p class="muted"><?= $area === 'backoffice' ? 'Manage orders and update their delivery state.' : 'Review placed orders and follow their delivery state.' ?></p>
        </div>
        <div class="actions">
            <?php if ($area === 'backoffice'): ?>
                <a class="btn btn-primary" href="<?= htmlspecialchars(route_url($area . '/orders/new'), ENT_QUOTES, 'UTF-8') ?>">New Order</a>
            <?php else: ?>
                <a class="btn btn-primary" href="<?= htmlspecialchars(route_url('frontoffice/products'), ENT_QUOTES, 'UTF-8') ?>">Order Products</a>
            <?php endif; ?>
            <a data-pdf-preview="true" href="<?= htmlspecialchars(route_url($area . '/orders/pdf', ['search' => (string) $orderFilters['search'], 'status' => (string) $orderFilters['status'], 'product_id' => (string) $orderFilters['product_id'], 'location' => (string) $orderFilters['location'], 'sort' => (string) $orderFilters['sort']]), ENT_QUOTES, 'UTF-8') ?>">Open PDF</a>
            <a href="<?= htmlspecialchars(route_url($area . '/products'), ENT_QUOTES, 'UTF-8') ?>">Products</a>
        </div>
    </div>
</div>

<div class="order-stats-grid">
    <div class="order-stat-card"><strong>Total Orders</strong><span class="metric"><?= htmlspecialchars((string) $orderStats['total_orders'], ENT_QUOTES, 'UTF-8') ?></span><span class="meta">All orders matching the current filters.</span></div>
    <div class="order-stat-card"><strong>Total Units</strong><span class="metric"><?= htmlspecialchars((string) $orderStats['total_units'], ENT_QUOTES, 'UTF-8') ?></span><span class="meta">Combined quantity across the visible orders.</span></div>
    <div class="order-stat-card"><strong>Revenue</strong><span class="metric">$<?= htmlspecialchars(number_format((float) $orderStats['total_revenue'], 2), ENT_QUOTES, 'UTF-8') ?></span><span class="meta">Total order value generated by this slice.</span></div>
    <div class="order-stat-card"><strong>Delivered</strong><span class="metric"><?= htmlspecialchars((string) $orderStats['shipped_orders'], ENT_QUOTES, 'UTF-8') ?></span><span class="meta">Orders already marked as delivered.</span></div>
</div>

<div class="card">
    <form method="get" action="<?= htmlspecialchars(base_url() . '/index.php', ENT_QUOTES, 'UTF-8') ?>" class="form-shell" style="margin-bottom:20px" data-live-search="true">
        <input type="hidden" name="route" value="<?= htmlspecialchars($area . '/orders', ENT_QUOTES, 'UTF-8') ?>">
        <div class="row">
            <div class="col-3">
                <div class="field">
                    <label for="order-search">Search</label>
                    <input id="order-search" type="text" name="search" placeholder="Search customer, email, product, or location" value="<?= htmlspecialchars((string) $orderFilters['search'], ENT_QUOTES, 'UTF-8') ?>">
                </div>
            </div>
            <div class="col-3">
                <div class="field">
                    <label for="order-product">Product</label>
                    <select id="order-product" name="product_id">
                        <option value="">All products</option>
                        <?php foreach ($products as $product): ?>
                            <option value="<?= htmlspecialchars((string) $product['id'], ENT_QUOTES, 'UTF-8') ?>" <?= (string) $orderFilters['product_id'] === (string) $product['id'] ? 'selected' : '' ?>><?= htmlspecialchars((string) $product['name'], ENT_QUOTES, 'UTF-8') ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="col-3">
                <div class="field">
                    <label for="order-status">Delivery State</label>
                    <select id="order-status" name="status">
                        <option value="">All states</option>
                        <?php foreach (['PENDING' => 'Not delivered', 'PAID' => 'Not delivered', 'SHIPPED' => 'Delivered', 'CANCELLED' => 'Cancelled'] as $status => $label): ?>
                            <option value="<?= htmlspecialchars($status, ENT_QUOTES, 'UTF-8') ?>" <?= (string) $orderFilters['status'] === $status ? 'selected' : '' ?>><?= htmlspecialchars($label, ENT_QUOTES, 'UTF-8') ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="col-2">
                <div class="field">
                    <label for="order-location">Map Pin</label>
                    <select id="order-location" name="location">
                        <option value="">Any</option>
                        <option value="pinned" <?= $orderFilters['location'] === 'pinned' ? 'selected' : '' ?>>Pinned</option>
                        <option value="missing" <?= $orderFilters['location'] === 'missing' ? 'selected' : '' ?>>Missing</option>
                    </select>
                </div>
            </div>
            <div class="col-1">
                <div class="field">
                    <label for="order-sort">Sort</label>
                    <select id="order-sort" name="sort">
                        <option value="created_desc" <?= $orderFilters['sort'] === 'created_desc' ? 'selected' : '' ?>>New</option>
                        <option value="customer_asc" <?= $orderFilters['sort'] === 'customer_asc' ? 'selected' : '' ?>>A-Z</option>
                        <option value="total_desc" <?= $orderFilters['sort'] === 'total_desc' ? 'selected' : '' ?>>$-</option>
                        <option value="total_asc" <?= $orderFilters['sort'] === 'total_asc' ? 'selected' : '' ?>>$+</option>
                        <option value="quantity_desc" <?= $orderFilters['sort'] === 'quantity_desc' ? 'selected' : '' ?>>Qty</option>
                        <option value="date_asc" <?= $orderFilters['sort'] === 'date_asc' ? 'selected' : '' ?>>Old</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="actions">
            <span class="muted">Filters update automatically while you type or change sort.</span>
            <a data-live-link="true" href="<?= htmlspecialchars(route_url($area . '/orders'), ENT_QUOTES, 'UTF-8') ?>">Reset</a>
        </div>
    </form>

    <?php if (($orders ?? []) === []): ?>
        <p class="muted" style="margin:0">No orders yet.</p>
    <?php else: ?>
        <table class="table">
            <thead>
                <tr>
                    <th>Customer</th>
                    <th>Product</th>
                    <th>Placed On</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Location</th>
                    <th>Delivery State</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($orders as $order): ?>
                    <?php $placedAt = !empty($order['created_at']) ? date('Y-m-d H:i', strtotime((string) $order['created_at'])) : (string) $order['order_date']; ?>
                    <tr>
                        <td>
                            <div><?= htmlspecialchars((string) $order['customer_name'], ENT_QUOTES, 'UTF-8') ?></div>
                            <div class="muted"><?= htmlspecialchars((string) $order['customer_email'], ENT_QUOTES, 'UTF-8') ?></div>
                        </td>
                        <td><?= htmlspecialchars((string) $order['product_name'], ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars($placedAt, ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars((string) $order['quantity'], ENT_QUOTES, 'UTF-8') ?></td>
                        <td>$<?= htmlspecialchars(number_format((float) $order['total_amount'], 2), ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars((string) (($order['delivery_location_name'] ?? '') ?: 'Not pinned'), ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars(order_status_label((string) $order['status']), ENT_QUOTES, 'UTF-8') ?></td>
                        <td>
                            <a href="<?= htmlspecialchars(route_url($area . '/orders/show', ['id' => (int) $order['id']]), ENT_QUOTES, 'UTF-8') ?>">View</a>
                            <?php if ($area === 'backoffice'): ?>
                                <a href="<?= htmlspecialchars(route_url($area . '/orders/edit', ['id' => (int) $order['id']]), ENT_QUOTES, 'UTF-8') ?>">Edit</a>
                                <form class="inline" method="post" action="<?= htmlspecialchars(route_url($area . '/orders/delete', ['id' => (int) $order['id']]), ENT_QUOTES, 'UTF-8') ?>" onsubmit="return confirm('Delete this order?');">
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
</div>
<script>
if (!window.AsteriaLiveUi) {
    window.AsteriaLiveUi = {
        liveDelayMs: 250,
        ensurePdfModal() {
            let modal = document.getElementById('asteria-pdf-modal');
            if (modal) return modal;
            modal = document.createElement('div');
            modal.id = 'asteria-pdf-modal';
            modal.innerHTML = '<div class="asteria-pdf-backdrop"></div><div class="asteria-pdf-dialog"><button type="button" class="asteria-pdf-close">Close</button><iframe title="PDF preview"></iframe></div>';
            document.body.appendChild(modal);
            const close = () => { modal.classList.remove('open'); const frame = modal.querySelector('iframe'); if (frame) frame.src = 'about:blank'; };
            modal.querySelector('.asteria-pdf-backdrop')?.addEventListener('click', close);
            modal.querySelector('.asteria-pdf-close')?.addEventListener('click', close);
            return modal;
        },
        openPdf(url) { const modal = this.ensurePdfModal(); const frame = modal.querySelector('iframe'); if (frame) frame.src = url; modal.classList.add('open'); },
        bindLiveForm(form, load) {
            if (form.dataset.liveBound === 'true') {
                return;
            }

            form.dataset.liveBound = 'true';
            let timer = 0;
            const submit = () => {
                const action = form.getAttribute('action') || location.pathname;
                const query = new URLSearchParams(new FormData(form)).toString();
                load(query ? action + '?' + query : action);
            };
            const schedule = () => {
                window.clearTimeout(timer);
                timer = window.setTimeout(submit, this.liveDelayMs);
            };

            form.addEventListener('submit', (event) => {
                event.preventDefault();
                submit();
            });

            form.querySelectorAll('input[type="text"], input[type="search"], input:not([type])').forEach((field) => {
                field.addEventListener('input', schedule);
            });

            form.querySelectorAll('select').forEach((field) => {
                field.addEventListener('change', submit);
            });
        },
        bindPanel(panelId) {
            const panel = document.getElementById(panelId);
            if (!panel) return;
            const load = (url) => fetch(url, {headers: {'X-Requested-With': 'XMLHttpRequest'}}).then(response => response.text()).then(html => {
                const next = new DOMParser().parseFromString(html, 'text/html').getElementById(panelId);
                if (!next) { window.location.href = url; return; }
                panel.replaceWith(next);
                history.pushState({}, '', url);
                this.bindPanel(panelId);
            }).catch(() => { window.location.href = url; });
            panel.querySelectorAll('form[data-live-search]').forEach((form) => this.bindLiveForm(form, load));
            panel.querySelectorAll('a[data-live-link]').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); load(link.href); }));
            panel.querySelectorAll('a[data-pdf-preview]').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); this.openPdf(link.href); }));
        }
    };
}
document.addEventListener('DOMContentLoaded', () => {
    window.AsteriaLiveUi.bindPanel('orders-live-panel');
});
</script>
<style>
#asteria-pdf-modal{position:fixed;inset:0;display:none;z-index:9999}.open#asteria-pdf-modal{display:block}
.asteria-pdf-backdrop{position:absolute;inset:0;background:rgba(15,23,42,.6)}
.asteria-pdf-dialog{position:relative;width:min(960px,92vw);height:min(88vh,820px);margin:4vh auto;background:#fff;border-radius:24px;overflow:hidden}
.asteria-pdf-close{position:absolute;top:14px;right:14px;z-index:2;border:0;border-radius:999px;padding:10px 14px;background:#0f172a;color:#fff}
.asteria-pdf-dialog iframe{width:100%;height:100%;border:0}
</style>
